CREATE TABLE "bank_accounts" (
	"id" serial PRIMARY KEY NOT NULL,
	"device_id" varchar NOT NULL,
	"bank_name" varchar NOT NULL,
	"bank_code" varchar NOT NULL,
	"account_number" varchar NOT NULL,
	"ifsc_code" varchar NOT NULL,
	"account_type" varchar NOT NULL,
	"account_holder_name" varchar NOT NULL,
	"balance" numeric(15, 2) DEFAULT '0.00',
	"daily_limit" numeric(12, 2) DEFAULT '100000.00',
	"monthly_limit" numeric(15, 2) DEFAULT '1000000.00',
	"is_active" boolean DEFAULT true,
	"is_primary" boolean DEFAULT false,
	"upi_id" varchar,
	"bank_logo" varchar,
	"last_transaction_at" timestamp,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "offline_devices" (
	"id" serial PRIMARY KEY NOT NULL,
	"device_id" varchar NOT NULL,
	"name" varchar NOT NULL,
	"type" varchar NOT NULL,
	"model" varchar NOT NULL,
	"mac_address" varchar NOT NULL,
	"bluetooth_version" varchar DEFAULT '5.0',
	"battery_level" integer DEFAULT 100,
	"signal_strength" integer DEFAULT 80,
	"distance" numeric(5, 2) DEFAULT '0.00',
	"last_seen" timestamp DEFAULT now(),
	"is_online" boolean DEFAULT true,
	"trust_level" varchar DEFAULT 'medium',
	"transaction_count" integer DEFAULT 0,
	"total_volume" numeric(15, 2) DEFAULT '0.00',
	"encryption" varchar DEFAULT 'AES-256',
	"location" text,
	"owner_id" varchar,
	"owner_phone" varchar,
	"owner_name" varchar,
	"profile_image" varchar,
	"rating" numeric(3, 2) DEFAULT '0.00',
	"review_count" integer DEFAULT 0,
	"is_verified" boolean DEFAULT false,
	"device_color" varchar DEFAULT '#1D4ED8',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "offline_devices_device_id_unique" UNIQUE("device_id")
);
--> statement-breakpoint
CREATE TABLE "offline_payment_sessions" (
	"id" serial PRIMARY KEY NOT NULL,
	"session_id" varchar NOT NULL,
	"from_device_id" varchar NOT NULL,
	"to_device_id" varchar NOT NULL,
	"connection_type" varchar DEFAULT 'bluetooth',
	"status" varchar DEFAULT 'initiated',
	"encryption_key" varchar,
	"connection_strength" integer DEFAULT 0,
	"connection_established_at" timestamp,
	"otp_verified_at" timestamp,
	"payment_completed_at" timestamp,
	"metadata" jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "offline_payment_sessions_session_id_unique" UNIQUE("session_id")
);
--> statement-breakpoint
CREATE TABLE "offline_transaction_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"transaction_id" varchar NOT NULL,
	"session_id" varchar NOT NULL,
	"from_device_id" varchar NOT NULL,
	"to_device_id" varchar NOT NULL,
	"amount" numeric(15, 2) NOT NULL,
	"currency" varchar DEFAULT 'INR',
	"description" text,
	"from_bank_account" integer NOT NULL,
	"to_bank_account" integer NOT NULL,
	"status" varchar DEFAULT 'pending',
	"failure_reason" text,
	"processing_time" integer,
	"fees" numeric(10, 2) DEFAULT '0.00',
	"net_amount" numeric(15, 2) NOT NULL,
	"confirmation_code" varchar,
	"bank_reference_number" varchar,
	"initiated_at" timestamp DEFAULT now(),
	"completed_at" timestamp,
	"synced_at" timestamp,
	CONSTRAINT "offline_transaction_logs_transaction_id_unique" UNIQUE("transaction_id")
);
--> statement-breakpoint
CREATE TABLE "otp_verifications" (
	"id" serial PRIMARY KEY NOT NULL,
	"from_device_id" varchar NOT NULL,
	"to_device_id" varchar NOT NULL,
	"otp_code" varchar NOT NULL,
	"purpose" varchar NOT NULL,
	"status" varchar DEFAULT 'pending',
	"attempts" integer DEFAULT 0,
	"max_attempts" integer DEFAULT 3,
	"expires_at" timestamp NOT NULL,
	"verified_at" timestamp,
	"metadata" jsonb,
	"created_at" timestamp DEFAULT now()
);
